### PR TITLE
Create example popup upon installation

### PR DESCRIPTION
**Pull request by fpcorso**
## Description
Creates an example popup when the plugin is first installed.

## Related Issue
Issue: #857 

## Types of changes
Creates a new popup when the plugin is installed and adds two new steps to the all popups page tour.

## Screenshots
image

## This has been tested in the following browsers
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

## Checklist:
- [x] My code has been tested in the latest version of WordPress.
- [x] My code does not have any warnings from ESLint.
- [x] My code does not have any warnings from StyleLint.
- [x] My code does not have any warnings from PHPCS.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards. 
- [x] All new functions and classes have code documentation.

### CODE REVIEW

**Comment by fpcorso** [comment]
@danieliser Thought we'd start with just one example popup to gauge interest and usage.

**Review by danieliser — APPROVED** [review]
I love that it attempts to send them to our site for each new user that goes to the example popup.

Should we have the last button on the initial set of pointers lead to editing the example popup so the tour can continue?

**Comment by fpcorso** [comment]
@danieliser I had thought of that but they will see this screen after they create their first popup, if they follow our preferred path:

1. Activate plugin
2. See welcome screen with button to create first popup
3. New popup screen with its tour
4. Then, either their frontend so they see their new popup or the all popups page where they would finally see this.

**Comment by danieliser** [comment]
@fpcorso will the example popup have a trigger that causes it to show for non admins right away? That might not be great, assuming that isn't what you meant by seeing it on front end.

**Comment by fpcorso** [comment]
@danieliser Ah, sorry. To clarify: I meant to see the popup **they created**, assuming they did so after the welcome screen. The example popup is disabled and would only show if the admin enabled it.

**Comment by danieliser** [comment]
Sounds perfect.

**Pull request merged**
