### PR TITLE
Feature/742 merge block functionality

### LINKED ISSUE #742: Merge Block Functionality

### PR DESCRIPTION
**Pull request by danieliser**
Closes #742

### CODE REVIEW

**Comment by fpcorso** [comment]
@danieliser What are all the features within this that I need to test out?

**Comment by danieliser** [comment]
@fpcorso The inline text popup trigger and making a block a trigger under block settings (not a super fan of this one but it works).

**Comment by fpcorso** [comment]
@danieliser Is the `dist` directory name for the block components confusing? Is that something we should change to `blocks` or something else at some point?

**Comment by fpcorso** [comment]
@danieliser Is the "Do default browser action?" question part of our component so that it's possible to customize the question or is that part of a WP component?

image

**Comment by fpcorso** [comment]
@danieliser I have a popup trigger and the button block with a popup controls on but, when I go to the front-end, neither works. The PM Admin bar says "No Popups Loaded?" when trying to manually open one.
image

**Comment by danieliser** [comment]
@fpcorso - So eventually we will move all code inside `/assets/` into `/dist/` for distribution.

WP core  & wp-scripts library default to `src` and `build`, but we use `build` for the prebuild.

In the near future we can rewrite that to match core going forward, but we need to rewite the `gulp` build routines to use another path.

`dist` / `build` won't be for just blocks, that is why I moved the block-editor functionality into a sub fodler.

---

2. We can absolutely change the text. Those are custom components under our control.

3. For now you still need to ensure the popup is loaded using targeting like any other click trigger. We can adjust that with some run time enqueuing of popups when they use the trigger shortcode etc.

The only part I don't like for the block level option in your last screenshot, is that the button isn't the one with the class added, the parent div is, just like page builders do unfortunately. In the future I'd like to selectively target based on block type. Button for example might target `.pum-trigger-block a.button`.

**Comment by fpcorso** [comment]
@danieliser This wasn't working on the pages that were targeted either last night which is why I mentioned it. However, that was before I realized the JS build errors.

After fixing now, I can verify that this is indeed working as intended.

**Pull request merged**
