### PR TITLE
Make menu icon use the menu icon color that's set in the site admin styling (also implement SVG instead of PNG in the process to support this)

### LINKED ISSUE #683: Double slash in dashboard icon url.
https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Types.php#L34

The plugin path already has an ending slash.

### PR DESCRIPTION
**Pull request by KZeni**
The icon needs to be called inline so WordPress then swaps out the SVG fill color for whatever menu icon color it should be (see https://stackoverflow.com/a/42265057/1275054 for more details).

Also, I added menu-icon.svg to the assets folder for reference (though it isn't actually called directly since the icon color is determined by having the SVG inline in the register_post_type parameters.) Figured it might be helpful to have that icon available as an SVG file (though having the SVG nor the PNG, for that matter, isn't required and I could just as easily see these removed from the plugin).

Regarding the icon itself, I tried to replicate the current menu icon while giving it a nice presence with some improvements in fidelity based on a higher resolution version of the icon.

As an aside, this should also make the issue https://github.com/PopupMaker/Popup-Maker/issues/683 safe to close due to the problematic area being fully replaced by this.

I have also posted this on the official WordPress.org support forum at: https://wordpress.org/support/topic/proposed-update-make-menu-icon-svg-use-the-set-menu-icon-color-4/

Resolves #683

### CODE REVIEW

**Comment by KZeni** [comment]
Okay, it looks like the use of borders within the SVG isn't playing entirely nicely. Update coming soon.

**Comment by KZeni** [comment]
Fixed. Just so you can see the benefit in doing this, here's the icon with various admin color schemes/themes & hover states.
Screen Shot 2019-11-27 at 7 12 25 PM
Screen Shot 2019-11-27 at 7 12 29 PM
Screen Shot 2019-11-27 at 7 12 05 PM
Screen Shot 2019-11-27 at 7 13 21 PM
Screen Shot 2019-11-27 at 7 13 26 PM
In effect, it just matches the icon's color with the appropriate color for the current admin color scheme (in addition to being vector-based for scalability, etc.) that the previous icon lacked.

**Comment by danieliser** [comment]
@KZeni - First appreciate any contributions from our community of users, so thanks.

Can I suggest one improvement, maybe move that <svg> code to a reusable function, maybe somewhere around here: `/includes/functions/general.php:119`

You could add an option argument $encode and use that to return the base64 encoded string when true. That way the SVG can be rendered as HTML or encoded and we can start reusing it in other places more quickly.

We did start to make new SVGs already, so we need to compare these vs the ones we created [here](https://github.com/PopupMaker/Block-Playground). Will have to leave it to the team to see which one's we end up using in the end, but your's are pretty clean so its a toss up. 

Otherwise we can get this merged into the next release.

**Comment by KZeni** [comment]
@danieliser Done. I've added it as a function (`pum_get_svg_icon`) where you can then pass `true` or `false` as a parameter (`$encode`) which then has it either output the base64 SVG code to be used for displaying it inline or just outputting the normal/raw SVG code, respectively. I then updated the two spots where the icon was being called previously so make use of this new function.

**Comment by danieliser** [comment]
@KZeni merged. Will be in v1.9 -beta later this month. FYI

**Pull request merged**
