### PR TITLE
Feature/597 popup cookie shortcode

### LINKED ISSUE #597: New shortcode to set cookies.
Allows users to set a cookie, disabling a popup, simply by inserting a shortcode on the page or tagging an html element with some extra parameters.

- [x] Should not trigger until visible.
- [x] Manual cookies should show this shortcode with atts prefilled for easy copy/paste.

### PR DESCRIPTION
**Pull request by danieliser**
Closes #597

### CODE REVIEW

**Comment by fpcorso** [comment]
@danieliser When the shortcode appears in the Popup Settings on slightly smaller displays, it pushes some of it outside the meta box:

image

Also, is "Manual JavaScript" still an appropriate name if they might be using a shortcode instead? Or, should we rename as just "Manual"?

**Comment by fpcorso** [comment]
@danieliser In addition to my previous comment, I cannot seem to get the shortcode to create the cookie correctly.

The popup has these trigger settings:
image

Inside the popup is a link to a thank you page:
image

The thank you page has the shortcode:
image

Which does get generated:
image

And, using the console, I am able to retrieve the args correctly:
image

However, the cookie is never generated and the popup continues to open.

**Comment by fpcorso** [comment]
Ah, just noticed that our JS is not enqueued on the thank you page since I don't have any popups on it. Should we enqueue in the shortcode handler?
image

**Comment by danieliser** [comment]
@fpcorso Ahh, good catch. My first thought was that you didn't build js assets. I haven't been committing build assets until we release (merge develop into master).

**Comment by danieliser** [comment]
- [x] Changed label to "**Manual**"
- [x] Enqueue scripts in the shortcode.
- [x] Added styles to fix the screen size issues: 
image

**Pull request merged**
