### PR TITLE
Feature/590 simplify form integrations

### LINKED ISSUE #590: Reorganize form integrations to reduce integration code and simplify interfaces.
Move all of these hard to maintain and separated functionalities into the popup editor directly.

#### Requirements:

- [x] Add new Form Submission Trigger #588
- [x] Add new Form Submission close option #589 
- [x] Add new Form Submission cookie event #725
- [x] Add integration support for non-ajax forms.

#### New Providers:
- [x] MC4WP
- [x] WP Forms
- [x] Caldera Forms

#### Optional (move to other issues if not done here)
- [ ] Add notice for users with existing form plugins that we support that they can manually migrate the settings for now until we build automated tools old methods will still work.

### PR DESCRIPTION
**Pull request by danieliser**
Resolves #590

### CODE REVIEW

**Comment by danieliser** [comment]
I believe this one is ready for testing and final merge @fpcorso.

**Comment by fpcorso** [comment]
Tested form trigger, form cookie, and form close for forms created with Ninja Forms. Testing others now...

**Comment by fpcorso** [comment]
Tested form trigger, form cookie, and form close for forms created with WP Forms. Everything looks good here.

**Comment by fpcorso** [comment]
MC4WP looks good too.

**Comment by fpcorso** [comment]
The form integrations and features have been tested @danieliser. We can get this merged.

**Pull request merged**
