### PR TITLE
Update from master

### PR DESCRIPTION
**Pull request by fpcorso**
Update developer with changes from master

### CODE REVIEW

**Comment by danieliser** [comment]
@fpcorso Was this a manual merge of a previous release? If so you should really install git-flow. These shouldn't be done from master, but rather from the tag of the version created off of master for the release.

**Comment by fpcorso** [comment]
@danieliser Normally, I would have gone from the tag of the version created but I also wanted to merge the new issue and pull request templates as I wanted to add to them as I completed other tasks during the 1.12 release which is why I merged from `master` for this one instead. 

Was there a better way to achieve that?

**Comment by danieliser** [comment]
@fpcorso Ahh, probably the "right" way would have been to make them features off of develop and merge them when we did a normal release, but this may be an exception to the rule as that doesn't fit the normal flows.

**Comment by danieliser** [comment]
Next time maybe just merge the tag like normal, then merge your side branches and then back merge master again into develop.

This way the normal release flow stays in tact and you can push changes directly to master and back to develop without worry.

**Pull request merged**
