### PR TITLE
Added KingComposer Page Builder Support

### PR DESCRIPTION
**Pull request by FearlessMode**
Hi, @danieliser 

I personally work with KingComposer.

I had planned to add support for KingComposer into Popup Maker while making my theme, but a customer in support requested this feature today so I added and tested it (lightly). All seems to be working fine (content editing, setting pages of PM and KC, no errors, etc.). I tested it in the GeneratePress theme.

Going forward, I'll be working with KingComposer as I have so I can help or keep tabs on this integration if any changes and submit the pull request if that time comes.

The customer already confirmed this is working as well.

### CODE REVIEW

**Comment by NoahjChampion** [comment]
Reference:
Site @ http://kingcomposer.com
Repo @ https://wordpress.org/plugins/kingcomposer/

**Comment by danieliser** [comment]
@NoahjChampion Nice. So just to confirm this adds support for their page builder in our popups? 

Will get this reviewed for v1.7. I have a lot of major improvements going into v1.7 for performance, ux & some major other integrations :+1:

**Comment by NoahjChampion** [comment]
@danieliser yes, exactly 💯 

And oh, nice! Looks great!

**Comment by danieliser** [comment]
@FearlessMode Can you clarify if the following if statement is correct for KB? I know that Beaver Builder uses the fl-builder slug as well so wanted to make sure that wasn't just left over code.

That said will be merging this into the release/1.7 branch rather than master but need to update it with the new PUM/pum prefixes rather than popmake as well.

**Comment by FearlessMode** [comment]
Hey @danieliser 

Yes, it's left over. 

And ok, great! Good deal.

**Comment by danieliser** [comment]
Ok so can you confirm both of those hooked filters/functions are required to make it work? Don't want any extra unneccesary code.

**Comment by FearlessMode** [comment]
Sure. Will do. 

I started working with Beaver Builder since this time. But I will reload it up for you and make sure. 

I will do that either shortly or later tonight.

**Comment by FearlessMode** [comment]
@danieliser 

All code is updated. You can review them again. Sorry, if I hit a commit button wrong that made the "checks fail"? I've never actually re-edited the code on a push before. So I just edited the files themselves to save them for the updates. 

Again to recap this will allow KingComposer to builder the popup content for a Popup. See screenshot below.

image

**Comment by danieliser** [comment]
@FearlessMode Don't worry about the checks. I have only set up 1/3 of the required code to make them work correctly so they always fail. Only started trying to add them this week though so hasn't gotten annoying enough yet to worry about.

I will likely be merging this manually rather than via PR because its going into release/1.7 branch which will likely result in merge issues if I try automatic. Either way it will be in there later tonight and in the beta  available next month.

Thanks for the effort, will make a note in the changelogs giving you credit.

**Comment by FearlessMode** [comment]
@danieliser 

Ok, great! And thanks about the credit. Never thought of it, lol. #Salute General. Have some good holiday time and a New Year man!!! Blessings. Enjoy!!!

**Pull request merged**
