### PR TITLE
Add class from theme title to theme overlay

### PR DESCRIPTION
**Pull request by bluantinoo**
solves this https://github.com/PopupMaker/Popup-Maker/issues/413

### CODE REVIEW

**Comment by danieliser** [comment]
@bluantinoo Was going to merge this but noticed you set it up to use the popup title rather than the theme title.

$this in the context your using it refers to the popup, not the theme. If I'm not mistaken you mean to use get_the_title( $this->get_theme_id() ).

I went ahead and added it for the release today v1.6.5. Appreciate the pull request, keep them coming.

**Comment by danieliser** [comment]
My bad, meant ```get_post_field( 'post_name', $this->get_theme_id() )```

**Comment by bluantinoo** [comment]
Your're right,  my bad.
Are you applying this edit or I make another pull?

**Comment by danieliser** [comment]
@bluantinoo - Already done, added it quickly before I pushed out the 1.6.5 release.

That  said v1.7 is under active dev as of late last night so feel free to submit some other patches if you get an itch ;)

**Pull request closed without merging**
